replicaCount: 3

image:
  pullPolicy: Always

ingress:
  enabled: true
  host: api.comfortablemove.com

hpa:
  minReplicas: 2
  maxReplicas: 10

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

config:
  environment: production
  logLevel: WARNING
