apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comfortablemove.fullname" . }}-secret
  labels:
    {{- include "comfortablemove.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  REDIS_URL: {{ .Values.secret.redisUrl | quote }}
  SEOUL_BUS_API_KEY: {{ .Values.secret.seoulBusApiKey | quote }}
  SECRET_KEY: {{ .Values.secret.secretKey | quote }}
