"""initial schema (users_devices, boarding_records)

Revision ID: f78b5d697607
Revises: 
Create Date: 2026-06-02 12:10:48.333732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f78b5d697607'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_devices',
    sa.Column('device_id', sa.UUID(), nullable=False, comment='기기 고유 ID'),
    sa.Column('device_token', sa.String(length=255), nullable=True, comment='iOS 기기 식별자 (선택)'),
    sa.Column('device_name', sa.String(length=100), nullable=True, comment='기기 이름 (예: iPhone 14 Pro)'),
    sa.Column('os_version', sa.String(length=20), nullable=True, comment='iOS 버전 (예: iOS 17.2)'),
    sa.Column('app_version', sa.String(length=20), nullable=True, comment='앱 버전 (예: 1.2.1)'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='임산부 인증 여부'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='출산 예정일 (임신 기간 추적용)'),
    sa.Column('sound_enabled', sa.Boolean(), nullable=False, comment='알림음 설정'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='기기 등록 시간'),
    sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='마지막 활동 시간'),
    sa.CheckConstraint("app_version ~ '^\\d+\\.\\d+\\.\\d+$'", name='chk_app_version'),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('device_token')
    )
    op.create_table('boarding_records',
    sa.Column('record_id', sa.UUID(), nullable=False, comment='기록 고유 ID'),
    sa.Column('device_id', sa.UUID(), nullable=True, comment='기기 ID (FK, 익명 사용자는 NULL)'),
    sa.Column('route_name', sa.String(length=20), nullable=False, comment='버스 노선명 (예: 721, 강동01)'),
    sa.Column('route_type', sa.String(length=10), nullable=True, comment='노선 유형 (간선, 지선, 마을 등)'),
    sa.Column('bus_device_id', sa.String(length=50), nullable=True, comment='BLE 기기 ID (예: BF_DREAM_721)'),
    sa.Column('station_id', sa.String(length=20), nullable=True, comment='정류장 ID (서울시 API 기준)'),
    sa.Column('station_name', sa.String(length=100), nullable=True, comment='정류장 이름 (예: 신설동역)'),
    sa.Column('ars_id', sa.String(length=20), nullable=True, comment='정류장 고유번호 (ARS ID)'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='탑승 위치 위도'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='탑승 위치 경도'),
    sa.Column('sound_enabled', sa.Boolean(), nullable=False, comment='알림음 사용 여부'),
    sa.Column('notification_status', sa.String(length=20), nullable=False, comment='전송 결과 (success, device_not_found, failure)'),
    sa.Column('boarded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='탑승 시간'),
    sa.CheckConstraint("notification_status IN ('success', 'device_not_found', 'failure')", name='chk_notification_status'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='chk_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='chk_longitude'),
    sa.ForeignKeyConstraint(['device_id'], ['users_devices.device_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('idx_boarding_records_boarded_at', 'boarding_records', ['boarded_at'], unique=False)
    op.create_index('idx_boarding_records_device', 'boarding_records', ['device_id'], unique=False)
    op.create_index('idx_boarding_records_device_date', 'boarding_records', ['device_id', 'boarded_at'], unique=False)
    op.create_index('idx_boarding_records_route', 'boarding_records', ['route_name'], unique=False)
    op.create_index('idx_boarding_records_station', 'boarding_records', ['station_id'], unique=False)
    op.create_index('idx_boarding_records_status', 'boarding_records', ['notification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_boarding_records_status', table_name='boarding_records')
    op.drop_index('idx_boarding_records_station', table_name='boarding_records')
    op.drop_index('idx_boarding_records_route', table_name='boarding_records')
    op.drop_index('idx_boarding_records_device_date', table_name='boarding_records')
    op.drop_index('idx_boarding_records_device', table_name='boarding_records')
    op.drop_index('idx_boarding_records_boarded_at', table_name='boarding_records')
    op.drop_table('boarding_records')
    op.drop_table('users_devices')
    # ### end Alembic commands ###
